### ISSUE TITLE
Expand CSS variables

### ISSUE THREAD

**Issue by dmitriid** [duetds/date-picker#41]
**Is your feature request related to a problem? Please describe.**

Some of the colors are re-used and may/will lead to difficulties when customising inputs. Specifically, borders:

```css
.duet-date__input {
    border: 1px solid var(--duet-color-text);
    border-radius: var(--duet-radius);
    color: var(--duet-color-text);
}
```

**Describe the solution you'd like**

Add a new variable, `--duet-color-border`. To maintain backards compatibility, it can fall back:

```
border: 1px solid var(--duet-color-border, var(--duet-border-text))
```

**Additional context**

See why here (duetds among material ui fields)

![Screenshot 2020-10-30 at 14 43 22](https://user-images.githubusercontent.com/32768/97712207-6e34e200-1abe-11eb-984d-f5d553ddd279.png)

----

By the way, the picker is amazing 🎉
